// Generated by Unloop
// Office Thermostat

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_boost_clicked(|| {
        println!("boost clicked");
    });
    
    app.on_away_clicked(|| {
        println!("away clicked");
    });
    

    
    app.run()
}
